#index:
#    path: /
#    controller: App\Controller\DefaultController::index


logout:
  path: /admin/logout
#controllers:
#  resource: '../src/Controller/Admin'
#  type: annotation
#  prefix: /admin
#  name_prefix: 'admin_'


