sonata_admin:
    title: 'Lyrics Admin'
#    templates:
#      user_block: '%kernel.project_dir%/templates/admin/layouts/menu.html.twig'

    dashboard:

        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                          <p><a href="/admin/mysql-to-elastic" class="btn btn-primary">MySQL To Elastic</a></p>
                          <p><a href="/admin/flush-redis" class="btn btn-warning">Flush Redis</a></p>

    security:
        handler: sonata.admin.security.handler.role

        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_ADMIN

sonata_block:
    blocks:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts: [admin]

