<?php
namespace common\models;

use common\helpers\AdminHelper;
use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;

/**
 * Singer model
 *
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property integer $hit
 * @property integer $status
 */
class Singer extends ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_PASSIVE = 0;

    // Cache Durations
    const CD_LIST = 6*60;
    const CD_ITEM = 60*60;

    public static $statuses = [
        self::STATUS_PASSIVE    => 'Passive',
        self::STATUS_ACTIVE     => 'Active',
    ];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%singers}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            ['slug', 'unique'],
            ['name', 'string', 'min' => 2, 'max' => 150],
            ['slug', 'string', 'min' => 1, 'max' => 100],
            ['slug', 'default', 'value' => 'n-a'],
            ['hit', 'number'],
            ['hit', 'default', 'value' => 0],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_PASSIVE]],
        ];
    }

    /**
     * @return array
     */
    public static function selectList()
    {
        return ArrayHelper::map(Singer::find()->orderBy('name ASC')->all(), 'id', 'name');
    }

    public static function getListWithCache($initial = false, $order = 'name', $pages = 14)
    {
        $singers    = Singer::find()->andWhere(['status' => self::STATUS_ACTIVE]);

        if (!empty($initial)) {
            if ($initial == '09') {
                $singers->andWhere("slug LIKE '0%' OR slug LIKE '1%' OR slug LIKE '2%' OR slug LIKE '3%' OR slug LIKE '4%' OR slug LIKE '5%' OR slug LIKE '6%' OR slug LIKE '7%' OR slug LIKE '8%' OR slug LIKE '9%'");
            } else {
                $singers->andWhere("slug LIKE '$initial%'");
            }
        }

        if ($pages === 'get_count') {
            return $singers->cache(self::CD_LIST)->count();
        } elseif (is_integer($pages) && $pages > 0) {
            $singers->offset(0)->limit($pages);
        } elseif (isset($pages->offset) && isset($pages->limit)) {
            $singers->offset($pages->offset)->limit($pages->limit);
        }

        if ($order == 'hit') {
            $singers->orderBy("hit DESC");
        } elseif ($order == 'name') {
            $singers->orderBy("slug ASC");
        }

        return $singers->cache(self::CD_LIST)->all();
    }

    public static function findOneBySlugWithCache($slug)
    {
        return Yii::$app->cache->getOrSet('find_singer_by_slug_'.$slug, function () use ($slug) {

            return Singer::findOne(['slug' => $slug, 'status' => self::STATUS_ACTIVE]);

        }, self::CD_ITEM);
    }

    public static function plusHit($id)
    {
        return Singer::updateAllCounters(['hit' => 1], ['id' => $id]);
    }

    public function createSlug($text, $c = 0)
    {
        $slug   = AdminHelper::slugify($text);

        if ($c > 0) {
            $slug   = $slug.'-'.$c;
        }

        if ($slug != '') {
            $slug_query = self::find()->andWhere(['slug' => $slug]);

            if ($slug_query->count() > 0) {
                return $this->createSlug($text, $c+1);
            }
        }

        return $slug;
    }

    /**
     * Relation
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSongs()
    {
        return $this->hasMany(Song::class, ['singer_id' => 'id']);
    }



    public function beforeValidate()
    {
        if ($this->slug == '' && $this->name != '') {
            $this->slug = $this->createSlug($this->name, $this->id);
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        ElasticItem::deleteItem($this->id, 'singer');

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        ElasticItem::saveItem($this->id, 'singer', $this);

        if (isset($changedAttributes['status'])) {
            // If a singer is active and it will be passive, we should make songs of the singer passive (SINGER_PASSIVE)
            if ($changedAttributes['status'] == 1 && $this->status == 0) {
                Song::updateAll(['status' => Song::STATUS_SINGER_PASSIVE],
                    ['singer_id' => $this->id, 'status' => Song::STATUS_ACTIVE]);
            }
            // We should do the direct opposite the previous one.
            elseif ($changedAttributes['status'] == 0 && $this->status == 1) {
                Song::updateAll(['status' => Song::STATUS_ACTIVE],
                    ['singer_id' => $this->id, 'status' => Song::STATUS_SINGER_PASSIVE]);
            }
        }

        parent::afterSave($insert, $changedAttributes);
    }

}